"""Create table Gor

Revision ID: 577ce278c5f1
Revises: 25a9d3f397fe
Create Date: 2020-04-05 09:35:36.190595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577ce278c5f1'
down_revision = '25a9d3f397fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama_gor', sa.String(length=140), nullable=False),
    sa.Column('alamat_gor', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gors_created_at'), 'gors', ['created_at'], unique=False)
    op.create_index(op.f('ix_gors_updated_at'), 'gors', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gors_updated_at'), table_name='gors')
    op.drop_index(op.f('ix_gors_created_at'), table_name='gors')
    op.drop_table('gors')
    # ### end Alembic commands ###
